// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvc1F4_eyGKrbnOvc9T8Dt8mIE9jbcePc',
    appId: '1:718555200790:web:93899006a545cc2c892437',
    messagingSenderId: '718555200790',
    projectId: 'mzinga-ac711',
    authDomain: 'mzinga-ac711.firebaseapp.com',
    storageBucket: 'mzinga-ac711.firebasestorage.app',
    measurementId: 'G-MB6HPWE40K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMTCAhpMQbpe_Bloxt0Isuf0RrRkkxp8',
    appId: '1:718555200790:android:609035e8e5f28d05892437',
    messagingSenderId: '718555200790',
    projectId: 'mzinga-ac711',
    storageBucket: 'mzinga-ac711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4C3PT07sG74MnNAe_yL4_dRTz4SFbx3c',
    appId: '1:718555200790:ios:fefeeade7ec9c154892437',
    messagingSenderId: '718555200790',
    projectId: 'mzinga-ac711',
    storageBucket: 'mzinga-ac711.firebasestorage.app',
    iosBundleId: 'com.example.mzinga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4C3PT07sG74MnNAe_yL4_dRTz4SFbx3c',
    appId: '1:718555200790:ios:fefeeade7ec9c154892437',
    messagingSenderId: '718555200790',
    projectId: 'mzinga-ac711',
    storageBucket: 'mzinga-ac711.firebasestorage.app',
    iosBundleId: 'com.example.mzinga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvc1F4_eyGKrbnOvc9T8Dt8mIE9jbcePc',
    appId: '1:718555200790:web:f81c248f4e441fb2892437',
    messagingSenderId: '718555200790',
    projectId: 'mzinga-ac711',
    authDomain: 'mzinga-ac711.firebaseapp.com',
    storageBucket: 'mzinga-ac711.firebasestorage.app',
    measurementId: 'G-LJ64YYTW9H',
  );
}
